version: 2
jobs:
  docker-build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.19
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.06.0-ce
      - run:
          name: Build and test docker image
          command: docker build . -t test;

workflows:
  version: 2
  cicd-pipeline:
    jobs:
      - docker-build
